<div class="col-xs-7 col-sm-6 col-sm-push-3">
    <div class="box ">
		<div class="box-header">
			<div class="box-name text-center">
				 <span>Edit Job Position</span>
			</div>
		</div>
		<div class="box-content">
            <?php echo $this->form->renderForm(false); ?>
            <div
				class="form-group <?php if (count($this->form->jobPositionName->getMessages())) echo 'has-error' ?>">
                <?php echo $this->form->jobPositionName->renderLabel(); ?>
                <div class="col-sm-6">
                    <?php echo $this->form->jobPositionName->renderViewHelper(); ?>
                    <?php echo $this->form->jobPositionName->renderErrors(); ?>
                </div>
			</div>
            <div class="form-group">
					<div class="box-footer">
						<div class="col-sm-offset-4 col-sm-6">
                            <?php echo $this->form->Save; ?>
                            <?php echo $this->form->Reset; ?>
                            <?php echo $this->form->Cancel;  ?>
                        </div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

