<?php
$this->headLink()->appendStylesheet(
        $this->baseUrl('/assets/css/redmond/jquery-ui.min.css'));
?>
<div class="col-xs-12 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3" style="margin-top:20px;">
	 <div class="box ">
		<div class="box-header">
			<div class="box-name text-center">
				 <span>Edit Profile</span>
			</div>
		</div>
		<div class="box-content">
			<div class="col-md-offset-2 col-sm-offset-3">
                <?php echo $this->form->renderForm(false); ?>
                <div
					class="form-group <?php if (count($this->form->partialCandidateForm->fullName->getMessages())) echo 'has-error' ?>">
                    <?php echo $this->form->partialCandidateForm->fullName->renderLabel(); ?>
                    <div class="col-sm-6">
                        <?php echo $this->form->partialCandidateForm->fullName->renderViewHelper(); ?>
                        <?php echo $this->form->partialCandidateForm->fullName->renderErrors(); ?>
                    </div>
				</div>
				<div
					class="form-group <?php if (count($this->form->partialCandidateForm->email->getMessages())) echo 'has-error' ?>">
                    <?php echo $this->form->partialCandidateForm->email->renderLabel(); ?>
                    <div class="col-sm-6">
                        <?php echo $this->form->partialCandidateForm->email->renderViewHelper(); ?>
                        <?php echo $this->form->partialCandidateForm->email->renderErrors(); ?>
                    </div>
				</div>
				<div
					class="form-group <?php if (count($this->form->partialCandidateForm->birthDate->getMessages())) echo 'has-error' ?>">
					<label class="col-sm-4 control-label text-danger" for="email">Date of
						Birth* :</label>
					<div class="col-sm-6">
                        <?php echo $this->form->partialCandidateForm->birthDate->renderUiWidgetElement(); ?>
                        <?php echo $this->form->partialCandidateForm->birthDate->renderErrors(); ?>
                    </div>
				</div>
				<div
					class="form-group <?php if (count($this->form->degree->getMessages())) echo 'has-error' ?>">
                    <?php echo $this->form->degree->renderLabel(); ?>
                    <div class="col-sm-6">
                        <?php echo $this->form->degree->renderViewHelper(); ?>
                        <?php echo $this->form->degree->renderErrors(); ?>
                    </div>
				</div>
				<div
					class="form-group <?php if (count($this->form->experienceYears->getMessages())) echo 'has-error' ?>">
                   <label for="exp" class="col-sm-4  control-label required">Experiance :</label>
                    <div class="col-sm-2">
                        <?php  echo $this->form->experienceYears->renderViewHelper(); ?>
                        <?php echo $this->form->experienceYears->renderErrors(); ?>
                    </div>
                   <div class="col-sm-1 no-padding "><small ><?php echo $this->form->experienceYears->renderLabel(); ?></small></div>
                    <div class="col-sm-2">
                        <?php  echo $this->form->experienceMonths->renderViewHelper(); ?>
                        <?php echo $this->form->experienceMonths->renderErrors(); ?>
                    </div>
                   <div class="col-sm-1 no-padding "><small><?php echo $this->form->experienceMonths->renderLabel(); ?></small></div>
                   
				</div>
				<div
					class="form-group <?php if (count($this->form->noticePeriod->getMessages())) echo 'has-error' ?>">
                    <?php echo $this->form->noticePeriod->renderLabel(); ?>
                    <div class="col-sm-6">
                        <?php echo $this->form->noticePeriod->renderViewHelper(); ?>
                        <?php echo $this->form->noticePeriod->renderErrors(); ?>
                    </div>
				</div>
				<div
					class="form-group <?php if (count($this->form->city->getMessages())) echo 'has-error' ?>">
                    <?php echo $this->form->city->renderLabel(); ?>
                    <div class="col-sm-6">
                        <?php echo $this->form->city->renderViewHelper(); ?>
                        <?php echo $this->form->city->renderErrors(); ?>
                    </div>
				</div>
				<div id="location"
					class="form-group <?php if (count($this->form->locality->getMessages())) echo 'has-error' ?>">
                    <?php echo $this->form->locality->renderLabel(); ?>
                    <div class="col-sm-6">
                        <?php echo $this->form->locality->renderViewHelper(); ?>
                        <?php echo $this->form->locality->renderErrors(); ?>
                    </div>
				</div>
				<div
					class="form-group <?php if (count($this->form->mobileNo->getMessages())) echo 'has-error' ?>">
                    <?php echo $this->form->mobileNo->renderLabel(); ?>
                    <div class="col-sm-6">
                        <?php echo $this->form->mobileNo->renderViewHelper(); ?>
                        <?php echo $this->form->mobileNo->renderErrors(); ?>
                    </div>
				</div>
                
				<div class="form-group">
					<div class="col-sm-10">
						<div class="box-footer">
							<div class="col-sm-offset-5 col-sm-6">
                                <?php echo $this->form->Save; ?>
                                <?php echo $this->form->Reset; ?>
                            </div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--
<script>
    $("#city").change(function(){
        if(this.value == '1'){
            $('#location').show();
        }else{
            $('#location').hide();
        }
        
    })
    $(document).ready(function(){
        if($("#city").val()== '1')
            $('#location').show();  
    })
    </script>-->