<div class="col-xs-8 col-sm-6 center-block">
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="panel-title">
				<i class="pull-right"></i>
				<h4>Change password</h4>
			</div>
		</div>
		<div class="panel-body">
            <?php echo $this->userForm->renderForm(false); ?>
            <div
				class="form-group <?php if (count($this->userForm->oldPassword->getMessages())) echo 'has-error' ?>">
                <?php echo $this->userForm->oldPassword->renderLabel(); ?>
                <div class="col-sm-6">
                    <?php echo $this->userForm->oldPassword->renderViewHelper(); ?>
                    <?php echo $this->userForm->oldPassword->renderErrors(); ?>
                </div>
			</div>
			<div
				class="form-group <?php if (count($this->userForm->newPassword->getMessages())) echo 'has-error' ?>">
                <?php echo $this->userForm->newPassword->renderLabel(); ?>
                <div class="col-sm-6">
                    <?php echo $this->userForm->newPassword->renderViewHelper(); ?>
                    <?php echo $this->userForm->newPassword->renderErrors(); ?>
                </div>
			</div>
			<div
				class="form-group <?php if (count($this->userForm->confNewPassword->getMessages())) echo 'has-error' ?>">
                <?php echo $this->userForm->confNewPassword->renderLabel(); ?>
                <div class="col-sm-6">
                    <?php echo $this->userForm->confNewPassword->renderViewHelper(); ?>
                    <?php echo $this->userForm->confNewPassword->renderErrors(); ?>
                </div>
			</div><div class="form-action">

				<div class="col-sm-9">
					<div class="box-footer">
						<div class="col-sm-offset-5 col-sm-12">
                            <?php echo $this->userForm->Save; ?>
                            <?php echo $this->userForm->Reset; ?>
                            <?php echo $this->userForm->Cancel; ?>
                        </div>
					</div>
				</div>
			</div>
		</div>
		</form>
	</div>
</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	// Add tooltip to form-controls
	$('.form-control').tooltip();
	
	// Load example of form validation
	LoadBootstrapValidatorScript(DemoFormValidator);
	// Add drag-n-drop feature to boxes
	WinMove();
});
</script>