<div class="col-xs-12 col-sm-12 center-block">
    <div class="box">
		<div class="box-header">
			<div class="box-name text-center">
				 <span>View Users</span>
			</div>
		</div>
		<div class="box-content">
			<table
				class="table table-bordered table-striped table-hover table-heading table-datatable"
				id="datatable-1">
				<thead>
					<th>Sr. No.</th>
					<th>Full Name</th>
					<th>Email/User name</th>
					<!--                <th>
                        Role
                    </th>-->
					<!--                <th>
                        Status
                    </th>-->
					<th>Action</th>
				</thead>
				<tbody>
                        <?php
                         if (count($this->users)): 
        $c = 1;
        foreach ($this->users as $user) :
            ?>
                            <tr
						id="usr<?php echo $this->escape($user['id']); ?>">
						<td>
                                    <?php echo $c++; ?>
                                </td>
						<td>
                                    <?php echo $this->escape($user['fullName']); ?>
                                </td>
						<td>
                                    <?php echo $this->escape($user['email']); ?>
                                </td>
						<!--                            <td>
                                <?php // echo $this->escape($user->getRole()->getRoleName());   ?>
                                </td>-->
						<!--                            <td>
                                    <a class="btn btn-default btn-mini" id="<?php //echo $this->escape($user['id']);  ?>" onClick="return changeStatus(this)" >
                                <?php //echo ($user['isEnabled'] == true) ? $this->escape('Active') : $this->escape('Inactive');   ?>
                                    </a>    
                                </td>-->
						<td><a class="btn btn-info btn-xs"
							href="<?php
            echo $this->url(
                    array(
                            'controller' => 'user',
                            'action' => 'edit',
                            'userId' => $this->escape($user['id']),
                            'module' => 'admin'
                    ), 'default', TRUE)?>"> <i
								class="glyphicon glyphicon-edit" title="edit"></i>
						</a> <a class="btn btn-danger btn-xs"
							href="<?php
            echo $this->url(
                    array(
                            'controller' => 'user',
                            'action' => 'delete',
                            'userId' => $this->escape($user['id']),
                            'module' => 'admin'
                    ), 'default', TRUE)?>"
							onclick="return deleteUser(<?php echo $this->escape($user['id']); ?>)">
								<i class="glyphicon glyphicon-trash" title="delete"></i>
						</a></td>
					</tr> 
                        <?php endforeach;
                        endif; ?>       
                    </tbody>



			</table>



                <?php
        // echo $this->paginationControl($this->users, 'Sliding',
        // 'partials/pagination.phtml');
        ?>
            </div>
	</div>
	<script>
            function deleteUser(userId) {
                var confirmAction = confirm("Are you sure to delete this user?");
                if (confirmAction) {

                    return true;
                }
                return false;
            }
        </script>
	 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/jquery.dataTables.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/ZeroClipboard.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/TableTools.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/dataTables.bootstrap.js') ?>"></script>
	<script type="text/javascript">
            // Run Datables plugin and create 3 variants of settings
                function MakeSelect2() {
                $('.dataTables_filter').each(function() {
                    $(this).find('label input[type=text]').attr('placeholder', 'Common Search');
                });
              }
            $(window).load(function() {
           	 TestTable1();
            	MakeSelect2();
                // Add Drag-n-Drop feature
                WinMove();
            });
        </script>
        