<div class="col-xs-12 col-sm-12 center-block">

    <?php if (count($this->candidates)): 
        
    
        ?>
        <div class="box">
		<div class="box-header">
			<div class="box-name text-center">
				<i class="fa fa-linux"></i> <span>Candidate Results</span>
			</div>

		</div>
		<div class="box-content no-padding table-responsive">
			<table
				class="table table-bordered table-striped table-hover table-heading table-datatable"
				id="datatable-2">
				<thead>
					<!--        <th>
                       User Id
                   </th>-->
					
					<th>Name</th>
				
					<th>Position</th>
					<th>Test</th>
					<th class="">Test date</th>
                    <th>Category wise details</th>
					<th>Total marks</th>

				</thead>
				<thead>
					<tr>
						

						<th><label><input type="text" name="search_fullName"
								value="Search  Name" class="search_init" /></label></th>
					
						<th><label><input type="text" name="search_position"
								value="Search position" class="search_init" /></label></th>
                                <th></th>
<!--						<th><label><input type="text" name="search_test"
								value="Search Test" class="search_init" /></label></th>-->
								<th class=""></th>
                                <th></th>
						<th>Scored/Total</th>
						
					</tr>
				</thead>
				<tbody>
                        <?php
        foreach ($this->candidates as $candidate) :
//            
//             var_dump($candidate->testResult);
            ?>
                            <tr
						id="usr<?php echo $this->escape($candidate->getID()); ?>">
						
						<td>
                                    <?php echo $this->escape($candidate->getCandidate()->getUser()->getfullName()); ?>
                                </td>
				
						<td>
                                    <?php echo $this->escape($candidate->getCandidate()->getJobPosition() ? $candidate->getCandidate()->getJobPosition()->getPosition() : 'Position not assigned'); ?>
                                </td>

						<td>
                                    <?php echo $this->escape(($candidate->getTest()) ? $candidate->getTest()->getTestName() : "No test assigned"); ?>
                                </td>
                                <td >
                                    <?php  echo $this->escape($candidate->getStartTime()->format('d-m-Y'));   ?>
                                </td>
                                <td>
                                    <table class="table table-bordered table-striped table-hover table-heading table-datatable">
                                        <thead>
                                            <tr>
                                                <th>
                                                    category name
                                                </th>
                                                <th>
                                                    scored/category total 
                                                </th>
                                                 <th>
                                                    time taken/category total time 
                                                </th>
                                            </tr>
                                        </thead>
                                       <?php foreach ($candidate->testResult as $categoryDet) : ?>
                                        <tr>
                                        <th>
                                            <?php print($this->escape($categoryDet['categoryName'])) ?>
                                        </th>
                                        <th>
                                            <?php print($this->escape($categoryDet['result']['scored'])) ?>/<?php print($this->escape($categoryDet['result']['catTotal'])) ?>
                                        </th>
                                        <th>
                                            <?php print($this->escape($categoryDet['result']['timeTaken'])) ?>/<?php print($this->escape($categoryDet['timeToFinish'])) ?>
                                        </th>
                                        </tr>
                                        <?php endforeach; ?>
                                           
                                    </table>
                                </td>
						<td>
                                    <?php echo $this->escape($candidate->getTotalMarks()); ?> / <?php echo $this->escape($candidate->total); ?> 
                                </td>
						<!--                            <td>
                                <?php //echo $this->escape(remark((int) $candidate->getRemark())); ?>
                                </td>-->
						
					</tr> 
                        <?php endforeach; ?>       
                    </tbody>
				<tfoot>

				</tfoot>
			</table>
			
                <?php
        // echo $this->paginationControl($this->candidates, 'Sliding',
        // 'partials/pagination.phtml');
        ?>
            </div>
	</div>
	    <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/jquery.dataTables.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/ZeroClipboard.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/TableTools.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/dataTables.bootstrap.js') ?>"></script>
	<script type="text/javascript">
    // Run Datables plugin and create 3 variants of settings 
           
          function MakeSelect2() {
                $('.dataTables_filter').each(function() {
                    $(this).find('label input[type=text]').remove();
                });
              
            }
            $(document).ready(function() {
                
                TestTable2(4);
                MakeSelect2();
                // Load Datatables and run plugin on tables 
            //    LoadDataTablesScripts(AllTables);
                // Add Drag-n-Drop feature
                WinMove();
            });
        </script>
        
     <?php else :
        echo 'No Test Result\'s To Display';
    

    endif;

    function remark ($remark)
    {
        switch ($remark) {
            case '0':
                $remark = 'Exam not given';
                break;
            case '1':
                $remark = 'Yet to Review';
                break;
            case '2':
                $remark = 'Waiting for result';
                break;
        }
        echo $remark;
    }
    ?>
