<div class="col-xs-12 col-sm-12 center-block">

    
        <div class="box">
		<div class="box-header">
			<div class="box-name text-center">
				<i class="fa fa-linux"></i> <span>Candidate position wise report</span>
			</div>

		</div>
		<div class="box-content no-padding table-responsive">
		<form class="form-inline" action="<?php echo $this->url(array('controller' => 'report','action'=>'position-wise-report','module'=>'admin'),'',TRUE) ?>" method="get" role="form">
            
            <label class="" for="exampleInputEmail2">Select position : </label>
            <div class="form-group"> <?php echo $this->positionDD->renderViewHelper(); ?></div>
            <label class="" for="exampleInputEmail2">From date :</label>
  <div class="form-group">
    
    <?php echo $this->datePicker("fromDate",  $this->fromDate,
             array(
    'dateFormat' => 'yy-mm-dd',
                'maxDate' => '+0')); ?>
  </div>
  <label class="" for="exampleInputEmail2">To date :</label>
  <div class="form-group">
    <label class="sr-only" for="exampleInputPassword2"></label>
   <?php echo $this->datePicker("toDate", $this->toDate,
             array(
                'dateFormat' => 'yy-mm-dd',
                'maxDate' => '0',
               )); ?>
  </div>
    <button type="submit" class="btn-info btn-circle"><i class="glyphicon glyphicon-refresh"></i></button>
</form>
			<table
				class="table table-bordered table-striped table-hover table-heading table-datatable"
				id="datatable-2">
				<thead>
					<!--        <th>
                       User Id
                   </th>-->
					
					<th>Name</th>
				
					<th>Position</th>
					<th>Test</th>
					<th class="">Test date</th>
                    <th>Category wise details</th>
					<th>Total marks</th>

				</thead>
				<thead>
					<tr>
						

						<th>
<!--                            <label><input type="text" name="search_fullName"
								value="Search  Name" class="search_init" /></label>-->
                        </th>					
                        <th>
<!--                            <label><input type="text" name="search_position"
								value="Search position" class="search_init" /></label>-->
                            
                        </th>
                                <th></th>
<!--						<th><label><input type="text" name="search_test"
								value="Search Test" class="search_init" /></label></th>-->
								<th class=""></th>
                                <th>
                <table  class="table table-bordered table-striped table-hover">
                    <tr class="col-sm-12" ><?php
                                        if (count($this->candidates)){
                                foreach ($this->testCategories as $cats ){
                                  echo "<th  class='text-center col-sm-2'>$cats</th>";
                                    
                                        } } ?>
                </tr>
                </table>
            </th>
						<th>Scored/Total</th>
						
					</tr>
				</thead>
				<tbody>
                        <?php if (count($this->candidates)): 
        
    
        
        foreach ($this->candidates as $candidate) :
//            
//             var_dump($candidate->testResult);
            ?>
                            <tr
						id="usr<?php echo $this->escape($candidate->getID()); ?>">
						
						<td>
                                    <?php echo $this->escape($candidate->getCandidate()->getUser()->getfullName()); ?>
                                </td>
				
						<td>
                                    <?php echo $this->escape($candidate->getCandidate()->getJobPosition() ? $candidate->getCandidate()->getJobPosition()->getPosition() : 'Position not assigned'); ?>
                                </td>

						<td>
                                    <?php echo $this->escape(($candidate->getTest()) ? $candidate->getTest()->getTestName() : "No test assigned"); ?>
                                </td>
                                <td >
                                    <?php  echo $this->escape($candidate->getStartTime()->format('d-m-Y'));   ?>
                                </td>
                                <td>
                                    <table class="table table-bordered table-striped table-hover markDispaly">
                                       <tr div class="col-sm-12">
                                       <?php 
            foreach ($this->testCategories as $key => $cats) :
                ?> <td  class="text-center col-sm-2"><?php 
                                       foreach ($candidate->testResult as $categoryDet) : ?>
                                        
                                      
                                            <?php
                                            if($key == $categoryDet['id']) :
                                            print($this->escape($categoryDet['result']['scored'])) ?>/<?php print($this->escape($categoryDet['result']['catTotal']));
                                      
                                                endif;
                                            ?>
                                            
                                       
                                      
                                        <?php endforeach; ?></td><?php 
                                        endforeach;
                                        ?>
                                             </tr>
                                    </table>
                                </td>
						<td>
                                    <?php echo $this->escape($candidate->getTotalMarks()); ?> / <?php echo $this->escape($candidate->total); ?> 
                                </td>
						<!--                            <td>
                                <?php //echo $this->escape(remark((int) $candidate->getRemark())); ?>
                                </td>-->
						
					</tr> 
                        <?php endforeach; 
                        
                            
    endif; ?>       
                    </tbody>
				<tfoot>

				</tfoot>
			</table>
			
                <?php
                
        // echo $this->paginationControl($this->candidates, 'Sliding',
        // 'partials/pagination.phtml');
        ?>
            </div>
	</div> 
    <?php
    $this->headLink()->appendStylesheet(
            $this->baseUrl(
                    '/assets/css/redmond/jquery-ui-1.10.4.custom.min.css'));
    ?>
	    <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/jquery.dataTables.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/ZeroClipboard.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/TableTools.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/dataTables.bootstrap.js') ?>"></script>
	<script type="text/javascript">
    // Run Datables plugin and create 3 variants of settings 
           
          function MakeSelect2() {
                $('.dataTables_filter').each(function() {
                     $(".hasDatepicker").addClass('form-control');
                    $(this).find('label input[type=text]').remove();
                });
              
            }
            $(document).ready(function() {
                
                TestTable2(3);
                MakeSelect2();
                // Load Datatables and run plugin on tables 
            //    LoadDataTablesScripts(AllTables);
                // Add Drag-n-Drop feature
                
            
                WinMove();
            });
           
               $('.markDispaly td').each(function(){
     if (($(this).html().trim() == "")){
      ($(this).html('N/A'));
    }
  })
        </script>
        
   <?php          


    function remark ($remark)
    {
        switch ($remark) {
            case '0':
                $remark = 'Exam not given';
                break;
            case '1':
                $remark = 'Yet to Review';
                break;
            case '2':
                $remark = 'Waiting for result';
                break;
        }
        echo $remark;
    }
    ?>
