<h2 class="page-header">Dashboard</h2>
<div class="col-xs-12 col-sm-12" id="dashboard_tabs">

	<div style="visibility: visible; position: relative;" class="row"
		id="dashboard-overview">
		<div class="col-sm-12 col-md-12" id="ow-marketplace">
			<h4 class="page-header">Candidate Info</h4>
			<div class="row placeholders">
				<div class="col-xs-6 col-sm-3 placeholder">
					<a
						href="<?php
    echo $this->url(
            array(
                    'controller' => 'candidate',
                    'module' => 'admin','action'=>'list'
            ))?>"
						title="view candidate">
						<button style="width: 100px; height: 100px;"
							class="btn-circle btn btn-success"><?php echo $this->escape($this->totalCandidate); ?></button>
						<h4>Candidates</h4>
					</a> <span class="text-muted">Total no. of candidates.</span>

				</div>
				<div class="col-xs-6 col-sm-3 placeholder">
					<a
						href="<?php
    echo $this->url(
            array(
                    'controller' => 'report',
                    'module' => 'admin'
            ))?>"
						title="view candidate report">
						<button style="width: 100px; height: 100px;"
							class="btn-circle btn btn-primary"><?php echo $this->escape($this->totalCandidateTestGiven); ?></button>
						<h4>Candidate given test</h4>
					</a> <span class="text-muted">Total no. of candidates given test.</span>
				</div>
				<div class="col-xs-6 col-sm-3 placeholder">
					<a
						href="<?php
    echo $this->url(
            array(
                    'controller' => 'candidate',
                    'action' => 'list',
                    'module' => 'admin',
                    'lastweek' => 1
            ))?>"
						title="view candidate report">
						<button style="width: 100px; height: 100px;" value="70"
							class="btn-circle btn btn-info"><?php echo $this->escape($this->lastweekCandidate); ?></button>
						<h4>Last week added</h4>
					</a> <span class="text-muted">No of candidate created last week.</span>
				</div>
				<div class="col-xs-6 col-sm-3 placeholder">
					<a
						href="<?php
    echo $this->url(
            array(
                    'controller' => 'report',
                    'module' => 'admin',
                    'review' => 2
            ))?>"
						title="view candidate report">
						<button style="width: 100px; height: 100px;" value="70"
							class="btn-circle btn btn-warning"><?php echo $this->escape($this->candidateToBeReview); ?></button>
						<h4>Total waiting for review</h4>
					</a> <span class="text-muted">Total no. of candidates yet to review
						test.</span>
				</div>

			</div>
		</div>
	</div>
</div>

<div class="col-sm-12 col-md-12" id="ow-marketplace">
	<h4 class="page-header">Test Info</h4>
	<div class="row placeholders">
		<div class="col-xs-6 col-sm-3 placeholder">
			<a
				href="<?php
    echo $this->url(
            array(
                    'controller' => 'test',
                    'action' => 'list',
                    'module' => 'admin'
            ))?>"
				title="view tests">
				<button style="width: 100px; height: 100px;" value="70"
					class="btn-circle btn btn-success"><?php echo $this->totalTests ?></button>
				<h4>Tests</h4>
			</a> <span class="text-muted">Total no. of tests.</span>

		</div>
		<div class="col-xs-6 col-sm-3 placeholder">
			<a
				href="<?php
    echo $this->url(
            array(
                    'controller' => 'question-category',
                    'module' => 'admin'
            ))?>"
				title="view question categories">
				<button style="width: 100px; height: 100px;" value="70"
					class="btn-circle btn btn-primary"><?php echo $this->totalCategories ?></button>
				<h4>Categories</h4>
			</a> <span class="text-muted">Total question categories.</span>
		</div>
		<div class="col-xs-6 col-sm-3 placeholder">
			<a
				href="<?php
    echo $this->url(
            array(
                    'controller' => 'question',
                    'action' => 'list',
                    'module' => 'admin'
            ))?>"
				title="view candidate report">
				<button style="width: 100px; height: 100px;" value="70"
					class="btn-circle btn btn-info"><?php echo $this->totalQuestions ?></button>
				<h4>Questions</h4>
			</a> <span class="text-muted">Total questions.</span>
		</div>
		<div class="col-xs-6 col-sm-3 placeholder">
			<a
				href="<?php
    echo $this->url(
            array(
                    'controller' => 'technology',
                    'action' => 'list',
                    'module' => 'admin'
            ))?>"
				title="view candidate report">
				<button style="width: 100px; height: 100px;" value="70"
					class="btn-circle btn btn-warning"><?php echo $this->totalTechnologies ?></button>
				<h4>Technologies</h4>
			</a> <span class="text-muted">Total technologies.</span>
		</div>

	</div>
</div>


