
<div class="col-xs-12 col-sm-12 center-block">
 
        <div class="box">
		<div class="box-header">
			<div class="box-name text-center">
				<i class="fa fa-linux"></i> <span>View candidates</span>
			</div>
		</div>
		<div class="box-content">
		<form class="form-inline" action="<?php echo $this->url(array('controller' => 'candidate','action'=>'list','module'=>'admin'),'',TRUE) ?>" method="get" role="form">
		<label class="" for="exampleInputEmail2">From date :</label>
  <div class="form-group">
    
    <?php echo $this->datePicker("fromDate",  $this->fromDate,
             array(
    'dateFormat' => 'yy-mm-dd',
                'maxDate' => '+0')); ?>
  </div>
  <label class="" for="exampleInputEmail2">To date :</label>
  <div class="form-group">
     <?php echo $this->datePicker("toDate", $this->toDate,
             array(
                'dateFormat' => 'yy-mm-dd',
                'maxDate' => '0',
               )); ?>
  </div>
    <button type="submit" class="btn-info btn-circle"><i class="glyphicon glyphicon-refresh"></i></button>
</form>

<div class="col-sm-12">
			<table
				class="table table-bordered table-striped table-hover table-heading table-datatable"
				id="datatable-2">
				
				<thead>
                <th class="hide">
                        User Id
                    </th>
					<th>Full name</th>
					<th>User name</th>
                    <th>Password</th>
					<th>Date created</th>
					<th>Position Applied for</th>
					<th>Test</th>
					<th>Action</th>
				</thead>
				<thead>
					<tr>
                        <th class="hide"></th>
						<th><label><input type="text" name="search_fullName"
								value="Search name" class="search_init" /></label></th>
						<th><label><input type="text" name="search_userName"
								value="Search username" class="search_init" /></label></th>
                                <th ><label class="hide"><input type="text" name="search_userName"
								value="Search username" class="search_init" /></label></th>
								<th><label><input type="text" name="search_date_created"
								value="Search date created" class="search_init" /></label></th>
						<th><label><input type="text" name="search_position"
								value="Search position" class="search_init" /></label></th>
						<th><label><input type="text" name="search_test"
								value="Search test" class="search_init" /></label></th>
						<th>edit/delete</th>
					</tr>
				</thead>
				<tbody>
                       <?php if (count($this->candidates)): ?>
                        <?php
        foreach ($this->candidates as $candidate) :
            ?>
                            <tr
						id="usr<?php echo $this->escape($candidate->getID()); ?>">
                                <td class="hide"><?php echo $this->escape($candidate->getID()); ?></td>
						<td>
                                    <?php echo $this->escape($candidate->getUser()->getfullName()); ?>
                                </td>
						<td>
                                    <?php echo $this->escape($candidate->getUser()->getEmail()); ?>
                                </td>
                                <td><?php echo $this->escape($candidate->getUser()->getDecryptedPassword()); ?></td>
                                                  <td>
                                <?php  echo $this->escape($candidate->getCreatedDate()->format('d-m-Y'));   ?>
                                </td>
						<td>
                                    <?php echo $this->escape($candidate->getJobPosition() ? $candidate->getJobPosition()->getPosition() : 'Position not assigned'); ?>
                                </td>
						<td>
                                    <?php echo $this->escape(($candidate->test) ? $candidate->test->getTestName() : "No test assigned"); ?>
                                </td>
						<td class="center"><a class="btn btn-info btn-xs"
							href="<?php
            echo $this->url(
                    array(
                            'controller' => 'candidate',
                            'action' => 'edit',
                            'candidateId' => $this->escape(
                                    $candidate->getUser()
                                        ->getId()),
                            'module' => 'admin'
                    ), 'default', TRUE)?>"> <i
								class="glyphicon glyphicon-edit" title="edit"></i>
						</a> <a class="btn btn-danger btn-xs"
							href="<?php
            echo $this->url(
                    array(
                            'controller' => 'candidate',
                            'action' => 'delete',
                            'candidateId' => $this->escape($candidate->getId()),
                            'module' => 'admin'
                    ), 'default', TRUE)?>"
							onclick="Javascript:return deleteUser(<?php echo $this->escape($candidate->getId()); ?>)">
								<i class="glyphicon glyphicon-trash" title="delete"></i>
						</a></td>
					</tr> 
                        <?php endforeach; ?>       
                    </tbody>
			    <?php endif; ?>
			</table>
			</div>
		</div>
            <?php
        // echo $this->paginationControl($this->candidates, 'Sliding',
        // 'partials/pagination.phtml');
        ?>
        </div>
</div>
<?php
$this->headLink()->appendStylesheet(
        $this->baseUrl('/assets/css/redmond/jquery-ui.min.css'));
?>

<script>
        function deleteUser(userId) {
            var confirmAction = confirm("Are you sure to delete this user?");
            if (confirmAction) {

                return true;
            }
            return false;
        }
    </script>
   
    <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/jquery.dataTables.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/ZeroClipboard.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/TableTools.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/dataTables.bootstrap.js') ?>"></script>
	<script type="text/javascript">
    // Run Datables plugin and create 3 variants of settings 
           
          function MakeSelect2() {
                $('.dataTables_filter').each(function() {
                     $(".hasDatepicker").addClass('form-control');
                    $(this).find('label input[type=text]').remove();
                });
            }
            $(document).ready(function() {
                
                TestTable2(0);
                
                MakeSelect2();
                // Load Datatables and run plugin on tables 
            //    LoadDataTablesScripts(AllTables);
                // Add Drag-n-Drop feature
                WinMove();
            });
        </script>

 