<div class="col-xs-12 col-sm-12 center-block">
    <div class="box">
		<div class="box-header">
			<div class="box-name text-center">
				<i class="fa fa-linux"></i> <span>View Questions</span>
			</div>

		</div>
		<div class="box-content">
			<table
				class="table table-bordered table-striped table-hover table-heading table-responsive table-datatable"
				id="datatable-2">
				<thead>
					<th>Sr. No.</th>
					<th>Question</th>
					<th>Question Category</th>
					<th>Question Type</th>
					<th>Marks</th>
					<th>Action</th>
				</thead>
				<thead>
					<tr>
						<th><label><input type="text" name="search_question" class="hide"
								value="Search Question" class="search_init" /></label></th>

						<th><label><input type="text" name="search_question"
								value="Search Question" class="search_init" /></label></th>
						<th><label><input type="text" name="search_category"
								value="Search category" class="search_init" /></label></th>
						<th><label><input type="text" name="search_type"
								value="Search question type" class="search_init" /></label></th>
						<th><label><input type="text" name="search_marks"
								value="Search marks" class="search_init" /></label></th>
						<th>edit/delete</th>
					</tr>
				</thead>
				<tbody>
                        <?php
                        if (count($this->questions)): 
        $c = 1;
        foreach ($this->questions as $question) :
            ?>
                            <tr
						id="cat<?php echo $this->escape($question->getID()); ?>">
						<td>
                                    <?php echo $c++; ?>
                                </td>
						<td>
                                    <?php echo (($question->getQuestion())); ?>
                                </td>
						<td>
                                    <?php echo $this->escape($question->getCategory()->getCategoryName()); ?>                 </td>
						<td>
                                    <?php echo $this->escape($question->getQuestionType()->getQuestionType()); ?>

                                </td>
						<td>
                                    <?php echo $this->escape(($question->getMarks()) ? $question->getMarks() : '0'); ?>

                                </td>
						<td><a class="btn btn-info btn-xs "
							href="<?php
            echo $this->url(
                    array(
                            'controller' => 'question',
                            'action' => 'edit',
                            'questionId' => $this->escape($question->getId()),
                            'module' => 'admin'
                    ), 'default', TRUE)?>"> <i
								class="glyphicon glyphicon-edit" title="edit"></i>
						</a> <a class="btn btn-danger btn-xs"
							href="<?php
            echo $this->url(
                    array(
                            'controller' => 'question',
                            'action' => 'delete',
                            'questionId' => $this->escape($question->getId()),
                            'module' => 'admin'
                    ), 'default', TRUE)?>"
							onclick="return deleteQuestion(<?php echo $this->escape($question->getId()); ?>)">
								<i class="glyphicon glyphicon-trash" title="delete"></i>
						</a></a></td>
					</tr> 
                        <?php endforeach;
                                endif; ?>       
                    </tbody>
				<tfoot>

				</tfoot>
			</table>
                <?php
        // TODO uncomment while zend pagination
        // echo $this->paginationControl($this->questions, 'Sliding',
        // 'partials/pagination.phtml');
        ?>
            </div>
	</div>

	<script>
            function deleteQuestion(questionId)
            {
                var confirmAction = confirm("Are you sure to delete this question?");
                if (confirmAction) {

                    return true;
                }
                return false;

            }
        </script>
	    <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/jquery.dataTables.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/ZeroClipboard.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/TableTools.js') ?>"></script>
			 <script
			src="<?php echo $this->baseUrl('/assets/plugins/datatables/dataTables.bootstrap.js') ?>"></script>
	<script type="text/javascript">
    // Run Datables plugin and create 3 variants of settings 
           
          function MakeSelect2() {
                $('.dataTables_filter').each(function() {
                    $(this).find('label input[type=text]').remove();
                });
              
            }
            $(document).ready(function() {
                
                TestTable2(0);
                MakeSelect2();
      
                // Add Drag-n-Drop feature
                WinMove();
            });
        </script>
