<div class="col-xs-7 col-sm-6 col-sm-push-3">
    <div class="box ">
		<div class="box-header">
			<div class="box-name text-center">
				 <span>Edit Technology</span>
			</div>
		</div>
		<div class="box-content">
             <?php echo $this->form->renderForm(false); ?>
            <div
				class="form-group <?php if (count($this->form->technologyName->getMessages())) echo 'has-error' ?>">
                <?php echo $this->form->technologyName->renderLabel(); ?>
                <div class="col-sm-6">
                    <?php echo $this->form->technologyName->renderViewHelper(); ?>
                    <?php echo $this->form->technologyName->renderErrors(); ?>
                </div>
		
            
			<div class="form-group">
                <div class="col-sm-3"></div>
				<div class="col-sm-push-1 col-sm-9">
                        <div class="col-sm-12">
                          <?php echo $this->form->Save; ?>
                            <?php echo $this->form->Reset; ?>
                            <?php echo $this->form->Cancel;  ?>
                        </div>
                </div>
			</div>
		</div>
	
	</div>
</div>


