<!DOCTYPE html>
<title>Ansh Online Interview App - Sign in</title>
<meta name="description" content="description">
<meta name="author" content="Evgeniya">
<meta name="keyword" content="keywords">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link
	href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"
	rel="stylesheet">
<link
	href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"
	rel="stylesheet">
<link
	href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"
	rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Righteous'
	rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lato'
	rel='stylesheet' type='text/css'>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
        <script src="//getbootstrap.com/docs-assets/js/html5shiv.js"></script>
        <script src="//getbootstrap.com/docs-assets/js/respond.min.js"></script>
<![endif]-->

<?php
echo $this->headLink();
echo $this->headStyle();
echo $this->headScript();
?>

<div class="container-fluid">
  
    <?php echo $this->layout()->content; ?>

</div>
